server:
  port: 8000
spring:
  application:
    name: service-order
  profiles:
    active: dev
  config:
    import:
      - nacos:service-order.yml
  cloud:
    nacos:
      server-addr: 192.168.95.135:8848
      config:
        import-check:
          enabled: false